version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: novaheda
      POSTGRES_USER: novaheda_user
      POSTGRES_PASSWORD: gatostem123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres

  npm:
    image: node:18-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local

networks:
  laravel-network:
    driver: bridge