name: Laravel Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: novaheda
          POSTGRES_USER: novaheda_user
          POSTGRES_PASSWORD: gatostem123
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql, pcntl, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          cp .env.example .env
          php artisan key:generate

      - name: Prepare environment
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear

      - name: Run migrations and seed
        run: php artisan migrate:fresh --seed

      - name: Execute tests
        run: php artisan test